# Website settings
url: "https://www.yesbolkulanekov.github.io"

# Internal nav
nav:
  main:
    writing: "/writing"
    speaking: "/speaking"
    projects: "/projects"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Yesbol Kulanbekov"
title: "Yesbol Kulanbekov"
description: "The home page of Yesbol Kulanbekov, iOS Developer"
thumbnail_path: "profile-photos/wolf.jpg"

# URLs
contact_urls:
  github:
    url: "https://github.com/yesbolkulanbekov"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:yesbolkulanekov@alumni.nu.edu.kz"
    label: "Email"
    value: "jim@ybrikman.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
repository: yesbolkulanbekov/yesbolkulanbekov.github.io

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
